- venv_overview.md
Added the following to the virtual environment page:  
```bash
$ deactivate
```
```bat
(mycalc) C:\> deactivate
```
> Added instructions to exit virtual env

- authors.md
> Add self as author

- authors.md
- countdown.py
Added "James Small" to authors.md
> Added my name to authors file

- AddTwoNumbers.py
- authors.md
made a simple function that returns the sum of two variables you pass in. I capitalized chalmer's name and added my name as well as a header "Authors:".
> Made a function to add two numbers and edited author page

- github_overview.md
Starting the GitHub documentation write up - incomplete...
> Starting GitHub Documentation

- README.md
- authors.md
- i_recur.py
- venv_overview.md
and other changes from before the math function part
> i recurred things

- README.md
- class_materials/authors.md
> README.md: Added hook for beginners. Polished other stuff.

- class_materials/authors.md
- class_materials/git_overview.md
I also added some additional information, which I thought would be helpful to include, however if the second commit is more advanced than what this file needs I can re make a pull request with just the first commit.
> Add git add/commit/push introduction

- class_materials/lesson_05_git_overview.md
Fleshed out the documentation for basic git operations. PR is to master directly since there are no conflicts and the changes are straightforward.
> document the most common git operations

- authors.md
- class_materials/lesson_01_intro_to_the_workshop.md
Specific instructions for setting up their fork and local clone of the repository we will be using on the 3/11 workshop
> instructions for checking out the specific repository we will be using

- class_materials/lesson_05_git_overview.md
Changes:
*Changed the 'Next Lesson:' link on the bottom of lesson_05 to link to the new lesson_06.
> updated link to lesson 6

- class_materials/lesson_07_intro_to_the_project.md
possible functions to add to RPN calc..
> added some suggested functions

- class_materials/lesson_07_intro_to_the_project.md
previously the existing and suggested functions were in a list.. have put them into tables to be easier to read
> lesson 7: functions into tables

- class_materials/lesson_06_github_part_deux.md
@chalmerlowe I changed the Next Lesson link from lesson_06_github_part_deux.md  to link to lesson_07_project_prep.md
> fixed link from lesson 06 to lesson 07

- README.md
Adds link from intro_to_sprinting/README.md to class_materials/README.md
> Overhaul - #70 - Adds link from default page to TOC

- class_materials/installing_tools.md
Changes:
- miniconda install: Suggest the use of Python 3. Honestly it doesn't matter, but they'll have to pick, so we can prime them here with what to pick.
- Show a possible error message and how to fix it.
Rationale:
- I got confused by both of these issues.
> miniconda install cleanup

- class_materials/installing_tools.md
Hopefully this strikes an adequate balance.
> Trivially change pip vs conda explanation

- class_materials/github_setup.md
I think this will be adequate.
> Use a 10 min timebox for GitHub setup

- class_materials/git_config.md
Changes:
- Set this to timebox at 5 min, because I think that should honestly be fine
- Avoid angle brackets for placeholders
> git setup: Add time estimate; decrease confusion

- class_materials/github_submit_pull_request.md
> Correct references to base and head fork

- class_materials/git_branch_merge.md
- class_materials/github_overview.md
Just noticed some quick changes to be made in the tutorial session.
The tutorial has been really helpful.
This is my first PR. Am I doing this right? :)
> Just cleaned up some endings of files

- class_materials/git_branch_merge.md
Added the green sticky image to git_branch_merge.md.
> Added green sticky image.

- class_materials/github_submit_pull_request.md
Adding a sticky to help people know when to put them on.
> add green sticky for 'submitting PR' step

- authors.md
> Added Brian Thorpe to authors list

- class_materials/lesson_07_project_prep.md
Changed lesson_07 to look like lesson_05. Students must change directory into their cloned repository to add a remote upstream.
> cd into project before running add upstream

- class_materials/installing_tools.md
> Updated installing_tools.md 

- class_materials/environment_overview.md
- class_materials/git_branch_merge.md
- class_materials/git_concepts.md
- class_materials/git_config.md
- class_materials/git_main_lifecycle.md
- class_materials/git_overview.md
- class_materials/virtual_environments.md
This pull request corrects some minor grammar inconsistencies found while reading through the tutorial.
> Minor Suggested Grammar Enhancement

- class_materials/installing_tools.md
#122 Take a look, hope this helps!
> Added Step X in installing_tools.md Issue #122

- class_materials/environment_overview.md
- class_materials/git_overview.md
- class_materials/github_overview.md
- class_materials/prereq_overview.md
> Updated four files to remove time box

- class_materials/github_setup.md
- class_materials/github_submit_pull_request.md
- class_materials/pull_request_tips.md
Fixed a small typo where the word 'to' was doubled.
> Changed 'to to' to 'to'

- class_materials/git_branch_merge.md
- class_materials/git_cloning.md
- class_materials/git_common_operations.md
- class_materials/git_concepts.md
- class_materials/git_config.md
- class_materials/git_main_lifecycle.md
- class_materials/git_merge_conflicts.md
- class_materials/git_overview.md
- class_materials/github_concepts.md
- class_materials/github_setup.md
- class_materials/github_submit_pull_request.md
> add links to Pro Git online book for fundamental git howtos

- class_materials/git_branch_merge.md
- class_materials/git_main_lifecycle.md
This PR:
- Changes single quotes to double for #110 
I think I got all of them. I only found commands with single quotes in 2 files, but if @paulproteus adds travis-ci it should catch any I may have missed.
> Single/Double Quotes Issue #110

- class_materials/installing_tools.md
Testing that I know how to properly do pull requests. And adding pipenv to mentioned environment management tools.
> Adding pipenv to mentioned working environments

- class_materials/git_branch_merge.md
> missing line between img and bold line

- README.md
Updated code style formatting for command line commands.
> updated code style formatting - Issue #139

- class_materials/git_main_lifecycle.md
> Fixed bullet/numbering issues in git_main_lifecycle

- class_materials/git_main_lifecycle.md
> removed comma

- class_materials/git_common_operations.md
Changed Beowolf.txt to beowulf.txt in file
> Changing Beowolf.txt

- authors.md
> Added my name - Jericho Guzman

- class_materials/setup_python.md
Added commands to activate virtualenv in Windows command line.
> Update setup_python.md 

- class_materials/git_branch_merge.md
- class_materials/git_cheatsheet.md
- class_materials/git_merge_conflicts.md
> Edits from master to main

- authors.md
- class_materials/git_cloning.md
> Fixed #196

- class_materials/git_branch_merge.md
Resolves your beginner friendly and help wanted issue #199. Thank you for the opportunity.
> Fix grammar error #199
